training_pipeline_config:
  pipeline_name: housing        # pipeline name that compoendt box 
  artifact_dir: artifact        #all the compoent we can get the outpput that store in artifact dir.its can be storage in that dir 

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data                 #data_ingestion_config= we created nametuple in config_entity
  tgz_download_dir: tgz_data             #give the infomation that are stoarge in yml file 
  ingested_dir: ingested_data            #these are some location of data
  ingested_train_dir: train
  ingested_test_dir: test 




data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml              #schema.yml +no of cou;lum and datatypes
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  add_bedroom_per_room: true                    #true it create the new colums
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml


model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models 